Get-PnpDevice | Where-Object {$_.Class-eq 'USB'}

#DIFFERENT CLASSES: 
# PRINTER      PRINTERS AND PRINT QUEUES
# NET          NETWORK DEVICES
# KEYBOARD     KEYBLOARD
# MOUSE        MICE AND OTHER POINTING DEVICES
## SOUND       AUDIO DEVICES
## DISPLAY     DISPLAY ADAPTERS
# DISKDRIVE    STORAGE DEVICES
# SYSTEM       SYSTEM LEVEL DEVICES LIKE CHIPSET COMPONENTS
# MEDIA        MEDIA CONTROLLERS LIKE DVD DRIVES
# BLUETOOTH    BLUETOOTH DEVICES
